

set_property PACKAGE_PIN G19 [get_ports {red[0]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]
set_property PACKAGE_PIN N19 [get_ports {red[3]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]

set_property PACKAGE_PIN P17 [get_ports {ldr_sensors[0]}]
set_property PACKAGE_PIN M19 [get_ports {ldr_sensors[1]}]
set_property PACKAGE_PIN L17 [get_ports {ldr_sensors[2]}]
set_property PACKAGE_PIN P18 [get_ports {ldr_sensors[3]}]
set_property PACKAGE_PIN B16 [get_ports {leds_r[3]}]
set_property PACKAGE_PIN B15 [get_ports {leds_r[4]}]
set_property PACKAGE_PIN A16 [get_ports {leds_r[5]}]
set_property PACKAGE_PIN A14 [get_ports {leds_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ldr_sensors[0]}]
set_property PACKAGE_PIN V16 [get_ports start_btn]
set_property IOSTANDARD LVCMOS33 [get_ports start_btn]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V17 [get_ports rst]

set_property PACKAGE_PIN A15 [get_ports {leds_r[2]}]
set_property PACKAGE_PIN A17 [get_ports {leds_r[1]}]
set_property PACKAGE_PIN C15 [get_ports {leds_r[0]}]
set_property PACKAGE_PIN N17 [get_ports {ldr_sensors[4]}]
set_property PACKAGE_PIN M18 [get_ports {ldr_sensors[5]}]
set_property PACKAGE_PIN K17 [get_ports {ldr_sensors[6]}]

